#!/bin/bash
# scripts/index-memory.sh [--dir memory] [--file MEMORY.md] [--check]
#
# Keeps an index of memory/*.md inside MEMORY.md, between markers.
#
# Why (T-J4, F4). Session Start step 5 read `MEMORY.md` and
# `memory/YYYY-MM-DD.md` "for today or yesterday". A live client project has 14
# memory files; the agent could reach two of them. Everything older was
# unreachable — not rarely read, never read, unless a human named the file by
# hand. Meanwhile DoD step 7 and Session End step 4 keep writing into that
# directory: the cost of recording is paid every session and the value is
# collected almost never.
#
# The fix is the cheapest thing that makes the whole directory reachable: one
# line per file in MEMORY.md, which is read every session anyway. Bodies stay
# on disk and are read on demand — the same "pointer in context, body on
# request" shape the harness already uses for skills.
#
# Deliberately NOT done here: renaming memory/YYYY-MM-DD.md to slugs. The
# ticket suggests it, but mass-renaming a project's accumulated notes to gain
# a nicer filename risks losing them for no reading benefit — the index is what
# makes them findable, not the name.
set -euo pipefail

command -v python3 >/dev/null 2>&1 || {
  echo "✗ python3 is required to index memory/." >&2
  exit 1
}

MEM_DIR="memory"
INDEX_FILE="MEMORY.md"
CHECK=0

while [ $# -gt 0 ]; do
  case "$1" in
    --dir)   MEM_DIR="${2:-}"; shift 2 ;;
    --file)  INDEX_FILE="${2:-}"; shift 2 ;;
    --check) CHECK=1; shift ;;
    -h|--help)
      echo "Usage: index-memory.sh [--dir memory] [--file MEMORY.md] [--check]"
      echo "  --check  exit 1 if the index is missing entries, instead of writing it"
      exit 0 ;;
    *) echo "✗ unknown argument: $1" >&2; exit 1 ;;
  esac
done

python3 - "$MEM_DIR" "$INDEX_FILE" "$CHECK" <<'PY'
import os
import re
import sys

mem_dir, index_file, check = sys.argv[1], sys.argv[2], sys.argv[3] == "1"

# The marker names the command that regenerates this block, so it has to be a
# command the reader can actually run. It used to say `scripts/index-memory.sh`
# — a path relative to the harness, pasted into a client project where no such
# file exists. Observed 2026-08-21: an agent ran it, got "no such file", and
# edited the generated block by hand instead — the one thing the marker tells
# it not to do. `session-end` is the shortcut that runs this, and it works from
# inside any adopted project.
START = "<!-- MEMORY-INDEX START — regenerated by `session-end`, do not edit by hand -->"
START_PREFIX = "<!-- MEMORY-INDEX START"
END = "<!-- MEMORY-INDEX END -->"

if not os.path.isdir(mem_dir):
    print(f"  · {mem_dir}/ not found — nothing to index")
    sys.exit(0)

files = sorted(
    (f for f in os.listdir(mem_dir) if f.endswith(".md")),
    reverse=True,  # newest first, matching PROGRESS.md
)

if not files:
    print(f"  · {mem_dir}/ has no .md files — nothing to index")
    sys.exit(0)


def summarize(path):
    """One line describing the file, from the best source available.

    Existing notes are titled with a bare date; new ones may carry a
    `description:` frontmatter. Both must produce something useful, or the
    index becomes a list of dates — which is what the directory listing
    already is.
    """
    with open(path, encoding="utf-8", errors="replace") as fh:
        lines = [line.rstrip("\n") for line in fh]

    if lines and lines[0].strip() == "---":
        for line in lines[1:]:
            if line.strip() == "---":
                break
            match = re.match(r"\s*description:\s*(.+)", line)
            if match:
                return match.group(1).strip().strip('"'), True

    heading = next((l for l in lines if l.startswith("# ")), "")
    text = heading[2:].strip()
    # "2026-08-11" alone says nothing the filename does not; "2026-07-20 —
    # Directus MCP: per-project generated config" does. Headings in the wild
    # wrap the date in filler on either side ("Memory — 2026-07-21",
    # "2026-07-17 Session"), so strip the filler and the date wherever they
    # sit, then judge what is left.
    stripped = text
    for _ in range(3):
        before = stripped
        stripped = re.sub(r"^(memory|session|notes)\b\s*[-—:]?\s*", "", stripped, flags=re.I)
        stripped = re.sub(r"^\d{4}-\d{2}-\d{2}\s*[-—:]?\s*", "", stripped)
        stripped = re.sub(r"\s*[-—:]?\s*(session|notes)$", "", stripped, flags=re.I)
        stripped = stripped.strip()
        if stripped == before:
            break
    if stripped:
        return stripped, True

    for line in lines:
        body = line.strip()
        if not body or body.startswith(("#", "---", "```")):
            continue
        body = re.sub(r"^[-*]\s*(\[[ x]\]\s*)?", "", body)
        body = re.sub(r"\*\*(.+?)\*\*", r"\1", body)
        if len(body) > 100:
            body = body[:97].rstrip() + "…"
        return body, False

    return "(no summary — add a `# YYYY-MM-DD — topic` heading)", False


entries = []
undescribed = []
for name in files:
    summary, explicit = summarize(os.path.join(mem_dir, name))
    entries.append(f"- [{name[:-3]}]({mem_dir}/{name}) — {summary}")
    if not explicit:
        undescribed.append(name)

block = [START, "", *entries, "", END]

if os.path.isfile(index_file):
    with open(index_file, encoding="utf-8") as fh:
        current = fh.read().split("\n")
else:
    current = ["# Long-term Memory", ""]

# Match the opening marker by prefix, not by exact text: the wording after
# "MEMORY-INDEX START" has changed once and may again, and an exact match
# would silently append a second index below the first.
start_at = next((i for i, line in enumerate(current)
                 if line.startswith(START_PREFIX)), None)
try:
    end_at = current.index(END)
except ValueError:
    end_at = None
if start_at is None or end_at is None or end_at < start_at:
    start_at = end_at = None
    existing_block = None
else:
    existing_block = current[start_at:end_at + 1]

if check:
    if existing_block is None:
        print(f"✗ {index_file} has no memory index — run: session-end", file=sys.stderr)
        sys.exit(1)
    missing = [e for e in entries if e.split(" — ")[0] not in "\n".join(existing_block)]
    if missing:
        print(f"✗ {index_file} index is out of date. Missing:", file=sys.stderr)
        for entry in missing:
            print(f"    {entry}", file=sys.stderr)
        print("  Run: bash scripts/index-memory.sh", file=sys.stderr)
        sys.exit(1)
    print(f"  ✓ {index_file}: memory index covers all {len(entries)} file(s)")
    sys.exit(0)

if existing_block == block:
    print(f"  ✓ {index_file}: memory index already current ({len(entries)} file(s))")
    sys.exit(0)

if start_at is not None:
    new_lines = current[:start_at] + block + current[end_at + 1:]
else:
    # First run: place the index right after the title, where a reader looks
    # for a table of contents, rather than at the end behind the prose.
    insert_at = 1 if current and current[0].startswith("# ") else 0
    heading = ["", "## Index — memory/", "",
               f"One line per note. Read a body only when the task touches it;",
               "these are notes from past sessions, so verify anything they",
               "name still exists before relying on it.", ""]
    new_lines = current[:insert_at] + heading + block + [""] + current[insert_at:]

with open(index_file, "w", encoding="utf-8") as fh:
    fh.write("\n".join(new_lines).rstrip("\n") + "\n")

print(f"  ✓ {index_file}: memory index updated ({len(entries)} file(s))")
if undescribed:
    print(f"    {len(undescribed)} note(s) have no topic in their heading — "
          f"the index shows their first line instead:")
    for name in undescribed[:5]:
        print(f"      {name}")
    if len(undescribed) > 5:
        print(f"      … and {len(undescribed) - 5} more")
PY
